### Send POST request to create a user
POST http://localhost:3000/auth/local/signup
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

### Send POST request sign in a user
POST http://localhost:3000/auth/local/signin
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

### Send POST request to logout a user
POST http://localhost:3000/auth/logout
Authorization: Bearer {{$jwt}}
Content-Type: application/json

### Send POST request to refresh token
POST http://localhost:3000/auth/refresh
Authorization: Bearer {{$jwt}}
Content-Type: application/json
